Refine Remote VEX support (TELDEVOPS-589)
- Allow for remote repository references to include option @branch
  specifier
- Issue a warning if a remote repository contains no .vex/ directory
- Add self-test for remote-vex

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -154,65 +154,86 @@ runs:
       run: |
         mkdir .remote-vex
         pushd .remote-vex
-        git init
+        git init -b main
         git config core.sparseCheckout true
         echo ".vex/*" > .git/info/sparse-checkout
         for REPO in $(echo "${{ inputs.remote-vex }}"); do
+          # Check for non-empty repository
+          REPO=$(echo "${REPO}" | tr -d '[:space:]')
           if [ -z "${REPO}" ]; then
             continue
           fi
 
-          git remote add -f origin https://github.com/${REPO}
-          git checkout main
+          # Determine branch, defaulting to main
+          BRANCH=${REPO##*@}
+          if [ "${REPO}" == "${BRANCH}" ]; then
+            BRANCH=main
+          else
+            REPO=${REPO%%@*}
+          fi
+
+          # Actually retrieve remote VEX statements
+          # Note the exit 0 to force us to continue even if we get a bad repository reference/branch
+          # In this case we'll hit the else branch and issue a Warning
+          echo "Retrieving Remote VEX statements from ${BRANCH} branch of ${REPO}"
+          git remote add -f origin https://github.com/${REPO} || exit 0
+          git checkout --force ${BRANCH} || exit 0
           if [ -d ".vex/" ]; then
-            mv .vex/* .
+            mv -fv .vex/*.json .
+            rm -Rf .vex/
+          else
+            echo "::warning title=No Remote VEX Statements in ${REPO}::Repository ${REPO} did not contain a .vex/ directory on its ${BRANCH} branch"
           fi
           git remote remove origin
         done
+
+        echo "Found the following Remote VEX Statements:"
+        ls -lh *.json
+
         popd
 
     # For convenience as there may be many VEX statements present merge them into a single VEX file that we then
     # pass into Trivy by setting the TRIVY_VEX environment variable
-    # This also serves to validate that the VEX statements are well formed as this will fail if they are not
+    # This also serves to validate that all the VEX statements are well formed as this will fail if they are not
     - name: Prepare VEX Statements
       id: prepare-vex
       shell: bash
       run: |
         # If local VEX statements exist merge them together
         if [ -d ".vex/" ]; then
-          vexctl merge .vex/*.json > .merged.openvex.json
+          vexctl merge .vex/*.json > merged.openvex.json
         fi
         # If any remote VEX statements exist merge them together as well
         if [ -d ".remote-vex/" ]; then
-          vexctl merge .remote-vex/*.json > .merged.remote.openvex.json
+          vexctl merge .remote-vex/*.json > merged.remote.openvex.json
         fi
 
         # If both local and remote VEX statements exist merge them together into a final
         # merged file
-        if [ -f .merged.openvex.json ] && [ -f .merged.remote.openvex.json ]; then
-          mv .merged.openvex.json .merged.local.openvex.json
-          vexctl merge .merged.local.openvex.json .merged.remote.openvex.json > .merged.openvex.json
+        # Or if only remote VEX statements exist rename that file, otherwise the next if block
+        # where we set TRIVY_VEX won't be triggered
+        if [ -f merged.openvex.json ] && [ -f merged.remote.openvex.json ]; then
+          mv merged.openvex.json merged.local.openvex.json
+          vexctl merge merged.local.openvex.json merged.remote.openvex.json > merged.openvex.json
+        elif [ -f merged.remote.openvex.json ]; then
+          mv merged.remote.openvex.json merged.openvex.json
         fi
 
         # Export the TRIVY_VEX environment variable if we have VEX statements available
-        if [ -f .merged.openvex.json ]; then
-          echo "TRIVY_VEX=.merged.openvex.json" >> $GITHUB_ENV
+        if [ -f merged.openvex.json ]; then
+          echo "TRIVY_VEX=merged.openvex.json" >> $GITHUB_ENV
           echo "prepared=true" >> $GITHUB_OUTPUT
         else
           echo "prepared=false" >> $GITHUB_OUTPUT
         fi
-
-        pwd
-        ls -lah
 
     - name: Upload VEX Statements (if any)
       if: ${{ steps.prepare-vex.outputs.prepared == 'true' }}
       uses: actions/upload-artifact@v4.4.3
       with:
         name: ${{ steps.sanitised.outputs.name }}-merged-vex-statements
-        path: .merged.openvex.json
+        path: merged.openvex.json
         retention-days: 30
-        include-hidden-files: true
 
     # Perform a full vulnerability to generate a full vulnerability report
     - name: Trivy Vulnerability Scan
