Fix bugs in handling remote-vex input (TELDEVOPS-589)
In some cases the remote-vex input handling code path could be
triggered, even though no repository references are actually provided.
A side effect of this is that some bash commands would then fail which
would incorrectly fail the entire action rather than continuing onwards.

diff --git a/.github/workflows/self-tests.yml b/.github/workflows/self-tests.yml
--- a/.github/workflows/self-tests.yml
+++ b/.github/workflows/self-tests.yml
@@ -144,6 +144,43 @@ jobs:
         run: |
           exit 1
 
+  empty-remote-vex:
+    runs-on: ubuntu-latest
+    needs: cache-images
+    steps:
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3.3.0
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Restore Cached Image
+        uses: telicent-oss/docker-image-cache-action@v1
+        with:
+          images: telicent/telicent-access-api:1.4.2
+          restore-only: true
+        
+      - name: Trivy Image Scan that Fails
+        id: trivy-scan
+        continue-on-error: true
+        uses: telicent-oss/trivy-action@v1
+        with:
+          scan-type: image
+          scan-ref: telicent/telicent-access-api:1.4.2
+          scan-name: empty-remote-vex
+          # Intentionally empty whitespace input for remote-vex
+          remote-vex: |
+               
+      - name: Fail if Trivy didn't fail
+        if: ${{ failure() && steps.trivy-scan.outcome != 'failed' }}
+        run: |
+          exit 1
+
+      - name: Download Scan Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ steps.trivy-scan.outputs.scan-results }}
+
   filesystem-scan:
     runs-on: ubuntu-latest
     steps:
